# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lazySacn' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for lazySacn
  pod 'TesseractOCRiOS'

  target 'lazySacnTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'lazySacnUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
